platform :ios, '9.0'

target 'swift 07 Clima' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swift 07 Clima
  	pod 'SwiftyJSON'
  	pod 'Alamofire'
  	pod 'SVProgressHUD'

end
